services:
  - name: 'Sensor Hub'
    uuid: 'D4:B7:67:56:DC:3B'
    default-timeout: 60s
    characteristics:
      - !Subscribe
        uuid: '00002a6e-0000-1000-8000-00805f9b34fb'
      - !Poll
        uuid: '00002a6e-0000-1000-8000-00805f9b34fb'
